services:
  servermanagerbot:
    image: ghcr.io/erfjab/servermanagerbot:latest
    restart: always
    env_file:
      - .env
    network_mode: "host"

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-servermanager}
      POSTGRES_USER: ${DATABASE_USERNAME:-servermanager}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-your_password_here}
      PGPORT: ${DATABASE_PORT:-5432}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: "host"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME:-servermanager}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: