from .env import (
    DEBUG,
    SQLALCHEMY_DATABASE_URL,
    TELEGRAM_ADMINS_ID,
    TELEGRAM_API_TOKEN,
    TRAFFIC_MONITOR_ENABLED,
    TRAFFIC_MONITOR_ALERT_PERCENT,
)
from .tg import BOT, DP

__all__ = [
    "DEBUG",
    "SQLALCHEMY_DATABASE_URL",
    "TELEGRAM_ADMINS_ID",
    "TELEGRAM_API_TOKEN",
    "TRAFFIC_MONITOR_ENABLED",
    "TRAFFIC_MONITOR_ALERT_PERCENT",
    "BOT",
    "DP",
]
